### ISSUE TITLE
App crashing if I change return value and build again

### ISSUE THREAD

**Issue by smkumar84** [Flash3001/Xamarin.BindingSwiftLibrarySample#3]
Your xamarin workspace build working fine. But xamarin app getting crash when i tried to change the swift return message   like "Values are came from swift" in your swift class. 
I dont know what is the reason to getting crash. 
Please help me to resolve this issue. I have already sent email reg this issue.

Need any config in xamarin ?

Thanks

**Comment by Flash3001** [comment]
@smkumar84 What is the message you are receiving? Please look at the crash logs from either device or simulator.
